---
- name: Deploy Static Website to IIS
  hosts: all
  tasks:
    - name: Check if Git is installed
      ansible.windows.win_shell: git --version
      register: git_check
      ignore_errors: true

    - name: Install Git using Winget (Modern Windows)
      ansible.windows.win_shell: winget install --id Git.Git -e --source winget --accept-source-agreements --accept-package-agreements
      when: git_check.rc != 0

    - name: Ensure IIS is installed
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Force Clean Directory
      ansible.windows.win_file:
        path: C:\inetpub\first-deployment
        state: absent

    - name: Create fresh directory
      ansible.windows.win_file:
        path: C:\inetpub\first-deployment
        state: directory

    - name: Clone the website from GitHub
      ansible.windows.win_shell: git clone https://github.com/ChereSenay/first-deployment.git C:\inetpub\first-deployment
      args:
        executable: cmd

    - name: Create IIS Website on Port 1020
      community.windows.win_iis_website:
        name: "FirstDeploymentTest"
        state: started
        port: 1020
        physical_path: C:\inetpub\first-deployment

    - name: Open Port 1020 in Windows Firewall
      community.windows.win_firewall_rule:
        name: "AllowPort1020"
        localport: 1020
        action: allow
        direction: in
        protocol: tcp
        state: present
