---
- name: Deploy Static Website to IIS
  hosts: all
  tasks:
    - name: Ensure IIS is installed
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Force Clean Directory
      ansible.windows.win_file:
        path: C:\inetpub\first-deployment
        state: absent

    - name: Create fresh directory
      ansible.windows.win_file:
        path: C:\inetpub\first-deployment
        state: directory

    - name: Clone the website from GitHub
      ansible.windows.win_shell: git clone https://github.com/ChereSenay/first-deployment.git C:\inetpub\first-deployment
      args:
        executable: cmd

    - name: Create IIS Website on Port 1020
      community.windows.win_iis_website:
        name: "FirstDeploymentTest"
        state: started
        port: 1020
        physical_path: C:\inetpub\first-deployment

    - name: Open Port 1020 in Windows Firewall
      community.windows.win_firewall_rule:
        name: "AllowPort1020"
        localport: 1020
        action: allow
        direction: in
        protocol: tcp
        state: present
